version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tag-extractor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - tag-extractor-network

  frontend:
    build: ./frontend
    container_name: tag-extractor-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tag-extractor-network

  redis:
    image: redis:alpine
    container_name: tag-extractor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - tag-extractor-network

networks:
  tag-extractor-network:
    driver: bridge

volumes:
  redis-data: